[package]
name = "crash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
hyper = { version = "0.14.26", features = ["client", "tcp", "http1", "stream"] }
hyper-rustls = "0.24.0"
rustls = "0.21.1"
tokio = { version = "1.28.1", features = ["full"] }
